package com.ef.pma.entities;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;


@Entity//mapping class to table in SQL database
public class Employee {

	// Columns in table
	@Id // id is auto generated by JPA
	@SequenceGenerator(name="employee_generator", sequenceName="employee_seq", allocationSize=1)
	@GeneratedValue(strategy= GenerationType.SEQUENCE, generator="employee_generator")	
	private long employeeId;
	private String firstName;
	private String lastName;
	private String email;
	
	/*//many employees could be assigned to one project
	@ManyToOne(cascade = {CascadeType.DETACH, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.PERSIST},
	fetch = FetchType.LAZY)//always use Lazy 
	@JoinColumn(name="project_id")
	private Project project;*/
	
	
	//many employees could be assigned to one project
	@ManyToMany(cascade = {CascadeType.DETACH, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.PERSIST},
	fetch = FetchType.LAZY)//always use Lazy 
	@JoinTable(name= "project_employee",
	joinColumns = @JoinColumn(name="employee_id"),
	inverseJoinColumns=  @JoinColumn(name="project_id"))
	private List<Project> projects;
	 
	
	//constructor
	public Employee() {}
	public Employee( String firstName, String lastName, String email) {
		super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
	}
	
	//getters and setters
	public long getEmployeeId() {
		return employeeId;
	}
	public void setEmployeeId(long employeeId) {
		this.employeeId = employeeId;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	
	
	public List<Project> getProjects() {
		return projects;
	}
	public void setProjects(List<Project> projects) {
		this.projects = projects;
	}
	
	
	
}//end